### ISSUE TITLE
VM username & password

### ISSUE THREAD

**Issue by Yicong-Huang** [uci-inf102-s18/vagrant-vm#4]
Trying to access the VM with VirtualBox. It requires the username and password for login. May I have those please?

**Comment by kajdreef** [comment]
Hi, this is explained in the [README](https://github.com/uci-inf102-s18/vagrant-vm), but the username and password should be by default: ```vagrant```. Also, you can just use ```vagrant ssh``` to login without having to use the username and password. Good luck!

**Comment by Yicong-Huang** [comment]
Yea I think I've missed that! Thank you! I am able to ssh perfectly, just curious to use GUI.
